/* tslint:disable max-line-length */
import { FileFormat, IFolderCollection } from '../models';
import { Map as map } from '../models/extensions';

export const extensions: IFolderCollection = {
  default: {
    folder: { icon: 'folder', format: FileFormat.svg },
  },
  supported: [
    { icon: 'aurelia', extensions: ['aurelia_project'], format: FileFormat.svg },
    { icon: 'aws', extensions: ['aws'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'binary', extensions: ['bin'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'bower', extensions: ['bower_components'], format: FileFormat.svg },
    { icon: 'composer', extensions: ['composer'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'client', extensions: ['client'], format: FileFormat.svg },
    { icon: 'config', extensions: ['config', 'ini', 'initializers'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'css', extensions: ['css'], map: [map.leadingUnderscore], format: FileFormat.svg },
    { icon: 'dist', extensions: ['dist', 'out', 'export', 'build', 'release'], format: FileFormat.svg },
    { icon: 'docker', extensions: ['docker'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'docs', extensions: ['docs'], format: FileFormat.svg },
    { icon: 'elasticbeanstalk', extensions: ['.elasticbeanstalk', '.ebextensions'], format: FileFormat.svg },
    { icon: 'flow', extensions: ['flow'], format: FileFormat.svg },
    { icon: 'fonts', extensions: ['fonts', 'font', 'fnt'], light: true, format: FileFormat.svg },
    { icon: 'git', extensions: ['.github', '.git'], format: FileFormat.svg },
    { icon: 'git', extensions: ['submodules'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'gcp', extensions: ['gcp'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'haxelib', extensions: ['haxelib'], format: FileFormat.svg },
    { icon: 'js', extensions: ['js'], map: [map.leadingUnderscore], format: FileFormat.svg },
    { icon: 'idea', extensions: ['.idea'], format: FileFormat.svg },
    { icon: 'images', extensions: ['images', 'image', 'img', 'icons', 'icon', 'ico'], format: FileFormat.svg },
    { icon: 'include', extensions: ['include', 'includes', 'incl'], format: FileFormat.svg },
    { icon: 'less', extensions: ['less'], map: [map.leadingUnderscore], format: FileFormat.svg },
    { icon: 'library', extensions: ['lib'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'locale', extensions: ['locale', 'locales', 'i18n', 'g11n'], format: FileFormat.svg },
    { icon: 'log', extensions: ['log', 'logs'], format: FileFormat.svg },
    { icon: 'node', extensions: ['node_modules'], light: true, format: FileFormat.svg },
    { icon: 'nuget', extensions: ['.nuget'], format: FileFormat.svg },
    { icon: 'package', extensions: ['package', 'packages'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'paket', extensions: ['.paket'], format: FileFormat.svg },
    { icon: 'php', extensions: ['php'], format: FileFormat.svg },
    { icon: 'plugin', extensions: ['plugin', 'plugins'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'private', extensions: ['private'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'public', extensions: ['public'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'meteor', extensions: ['.meteor'], light: true, format: FileFormat.svg },
    { icon: 'sass', extensions: ['sass', 'scss'], map: [map.leadingUnderscore], light: true, format: FileFormat.svg },
    { icon: 'script', extensions: ['script', 'scripts'], format: FileFormat.svg },
    { icon: 'src', extensions: ['src', 'source', 'sources'], format: FileFormat.svg },
    { icon: 'server', extensions: ['server'], format: FileFormat.svg },
    { icon: 'style', extensions: ['style', 'styles'], format: FileFormat.svg },
    { icon: 'test', extensions: ['tests', 'test', 'spec', 'specs'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'test', extensions: ['_tests_', '_test_'], map: [map.fullyUnderscored], format: FileFormat.svg },
    { icon: 'tools', extensions: ['tools'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'typescript', extensions: ['typescript', 'ts'], map: [map.leadingUnderscore], format: FileFormat.svg },
    { icon: 'typings', extensions: ['typings'], format: FileFormat.svg },
    { icon: 'typings2', extensions: ['typings'], format: FileFormat.svg, disabled: true },
    { icon: 'vagrant', extensions: ['vagrant'], map: [map.dotted], format: FileFormat.svg },
    { icon: 'view', extensions: ['html', 'view', 'views'], map: [map.leadingUnderscore], format: FileFormat.svg },
    { icon: 'vs', extensions: ['.vs'], format: FileFormat.svg },
    { icon: 'vscode', extensions: ['.vscode'], format: FileFormat.svg },
    { icon: 'vscode_test', extensions: ['.vscode-test'], format: FileFormat.svg },
    { icon: 'webpack', extensions: ['webpack'], format: FileFormat.svg },
  ],
};
